name: Cloud EXE Builder
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Using the newest stable version

      - name: Install & Package
        run: |
          npm install
          npx pkg . --target node18-win-x64 --output survival-game.exe
        # The "." tells pkg to look at your package.json to find the start file
        
      - name: Save EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-game-file
          path: survival-game.exe
